### ISSUE TITLE
JS API hangs/freezes node

### ISSUE THREAD

**Issue by foobardevpro** [theseanl/tscc#70]
```
const tscc = require('@tscc/tscc').default

return tscc({
	modules: {
		'dist/bundle': 'src/main.ts'
	}
}, 'somepath')
```

Most of the time, when I run this script, node will hang (even freeze; can barely force terminal to close) after "compilation success" is printed in console and never exit.

Only rarely, will it exit normally. But the compilation itself always works.

Issue occurs both with java compiler and windows compiler (OS is Windows 10, 64-bit).

Edit: Upon further testing, issue seems to be resolved when I comment out the spinner related logic in Logger.js

**Comment by theseanl** [comment]
This is strange, could it be that the terminal emulator you are using does not supports or somehow misbehaves for `\033[s` or `\033[u` escape sequences?

**Comment by foobardevpro** [comment]
Hi. Both cmd and powershell freeze. Git bash doesn't freeze but the tscc command never exits as well, and trying to close git bash warns me "processes are running in session".

Are there any tests I should try?

**Comment by theseanl** [comment]
I've published a new version, hopefully this will fix an issue with never-resolving promises. I suspect that this is related to a terminal emulator you are using. I don't have a Windows machine available right now, I'll try in a few weeks. In the meantime, if you are using Windows 10, you may try it with bash shell for WSL.

**Comment by foobardevpro** [comment]
Issue still persists. But does not occur with bash shell for WSL (even pre-commit).

**Comment by theseanl** [comment]
I was able to get access to a Windows machine, and was able to reproduce the issue. Upon some debugging, it seemed to be an issue related to `vinyl-fs` module. At linehttps://github.com/theseanl/tscc/blob/master/packages/tscc/src/tscc.ts#L200, the previous stream 'emits' data correctly but the `vfs.dest` stream is doing nothing, not emitting any events and so on. This seems to be an issue specific to Windows and requires some digging into gulp modules. I'll give another try soon.

**Comment by theseanl** [comment]
Could you check with 0.4.3?

**Comment by foobardevpro** [comment]
Issue resolved in 0.4.3 :)

**Comment by theseanl** [comment]
Good! For reference, it seems that the issue was caused by some codes along the line https://github.com/sindresorhus/ora/blob/master/index.js#L215. It's still unknown that how and why this affects only Windows machines and affects seemingly unrelated `vinyl-fs` module. I do not have time to dig on this deeper. Anyway overriding `process.stdin.emit` looks pretty dangerous and it'd be better to disable it.
